# Pandas

# Key feature of Pandas

# benifit of using Pandas:

# Datastructure----

1. Panda Series
2. Panda DataFrame

# Panda Series

In [2]:
import pandas as pd
import numpy as np

In [5]:
#creating an array

a=np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [4]:
#coverting it into series
a=pd.Series(np.arange(1,7))
print(a)             #we did not give the index, so the index order based on the given data 

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32


In [7]:
a=pd.Series(np.arange(1,7),dtype=np.int64)     #here we change the data type
print(a)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64


In [9]:
#if we want to change the index
a=pd.Series(np.arange(1,7),dtype=np.int64,index=['a','b','c','d','e','f'])     #here we change the data type
print(a)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64


In [20]:
c=pd.Series(65,index=[1,2,3,4,5,6])
print(c)

1    65
2    65
3    65
4    65
5    65
6    65
dtype: int64


In [21]:
d=np.array(['Ram','Shyam','Sita','Gita'])
print(d)
print(d.ndim)     #we use ndim for check the dimension
print()
e=pd.Series(np.array(['Ram','Shyam','Sita','Gita']))
print(e)

['Ram' 'Shyam' 'Sita' 'Gita']
1

0      Ram
1    Shyam
2     Sita
3     Gita
dtype: object


### we can also do indexing and slicing

In [10]:
b=pd.Series(np.arange(1,10),index=['row1','row2','row3','row4','row5','row6','row7','row8','row9'])
print(b)

row1    1
row2    2
row3    3
row4    4
row5    5
row6    6
row7    7
row8    8
row9    9
dtype: int32


In [11]:
b['row6':'row9']    #retrieve records by label index: 0 to n

row6    6
row7    7
row8    8
row9    9
dtype: int32

In [13]:
b['row1':'row3']

row1    1
row2    2
row3    3
dtype: int32

In [14]:
b[0:4]    # position based indexing : 0 to n-1 5 

row1    1
row2    2
row3    3
row4    4
dtype: int32

In [16]:
b[7:9]

row8    8
row9    9
dtype: int32

In [18]:
b['row9']   #retrieve records by numeric index

9

In [19]:
b[7]

8

In [25]:
x = pd.Series([1,2,3],index = ['a','b','c'])  
                                                     #retrieve the last element  
print(x)
print("\nAccessing index _ value = " , x['c'])       #\n for changing the line

a    1
b    2
c    3
dtype: int64

Accessing index _ value =  3


# Pandas DataFrame

### Parameter

In [43]:
a=np.arange(1,61).reshape(12,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]
 [41 42 43 44 45]
 [46 47 48 49 50]
 [51 52 53 54 55]
 [56 57 58 59 60]]


In [41]:
df=pd.DataFrame(a)
df

0   1   2   3   4
0    1   2   3   4   5
1    6   7   8   9  10
2   11  12  13  14  15
3   16  17  18  19  20
4   21  22  23  24  25
5   26  27  28  29  30
6   31  32  33  34  35
7   36  37  38  39  40
8   41  42  43  44  45
9   46  47  48  49  50
10  51  52  53  54  55
11  56  57  58  59  60

In [44]:
df=pd.DataFrame(a , columns = ['col1','col2','col3','col4','col5'])
df

col1  col2  col3  col4  col5
0      1     2     3     4     5
1      6     7     8     9    10
2     11    12    13    14    15
3     16    17    18    19    20
4     21    22    23    24    25
5     26    27    28    29    30
6     31    32    33    34    35
7     36    37    38    39    40
8     41    42    43    44    45
9     46    47    48    49    50
10    51    52    53    54    55
11    56    57    58    59    60

In [45]:
#if we want to save the data from excel

df.to_csv("df.csv",index=False)   #index=false means we didnot want to create index in excel

In [46]:
df2=pd.DataFrame(np.arange(1,37).reshape(6,6))
df2

0   1   2   3   4   5
0   1   2   3   4   5   6
1   7   8   9  10  11  12
2  13  14  15  16  17  18
3  19  20  21  22  23  24
4  25  26  27  28  29  30
5  31  32  33  34  35  36

In [48]:
#if we want to change index and column name both

i=['row1','row2','row3','row4','row5','row6']
c=['col1','col2','col3','col4','col5','col6']
df3=pd.DataFrame(np.arange(1,37).reshape(6,6), index=i,columns=c)
df3

col1  col2  col3  col4  col5  col6
row1     1     2     3     4     5     6
row2     7     8     9    10    11    12
row3    13    14    15    16    17    18
row4    19    20    21    22    23    24
row5    25    26    27    28    29    30
row6    31    32    33    34    35    36

In [51]:
df3.shape               

(6, 6)

### slicing operations:

## loc function()

In [55]:
df4= pd.DataFrame(np.arange(1,61).reshape(6,10))
df4

0   1   2   3   4   5   6   7   8   9
0   1   2   3   4   5   6   7   8   9  10
1  11  12  13  14  15  16  17  18  19  20
2  21  22  23  24  25  26  27  28  29  30
3  31  32  33  34  35  36  37  38  39  40
4  41  42  43  44  45  46  47  48  49  50
5  51  52  53  54  55  56  57  58  59  60

In [56]:
 df4.loc[2:3,3:5]

3   4   5
2  24  25  26
3  34  35  36

In [57]:
#if we want to extract only 44
df4.loc[4,3]  #4 is for row then , and 3 for column

44

In [58]:
#if we want to extract 34-38

df4.loc[3,4:7]

4    35
5    36
6    37
7    38
Name: 3, dtype: int32

In [60]:
df4.loc[3,5]

36

# iloc function()

iloc used for position based index

In [3]:
a=pd.DataFrame(np.arange(1,61).reshape(6,10))
a

0   1   2   3   4   5   6   7   8   9
0   1   2   3   4   5   6   7   8   9  10
1  11  12  13  14  15  16  17  18  19  20
2  21  22  23  24  25  26  27  28  29  30
3  31  32  33  34  35  36  37  38  39  40
4  41  42  43  44  45  46  47  48  49  50
5  51  52  53  54  55  56  57  58  59  60

In [7]:
#if we want to extract 60
a.iloc[5:,9:]

9
5  60

In [8]:
a.iloc[2:4,2:5]

2   3   4
2  23  24  25
3  33  34  35

In [9]:
a.iloc[4]

0    41
1    42
2    43
3    44
4    45
5    46
6    47
7    48
8    49
9    50
Name: 4, dtype: int32

In [10]:
a.iloc[:,4]

0     5
1    15
2    25
3    35
4    45
5    55
Name: 4, dtype: int32

# head()

In [11]:
# head() is used to print the first five elements

In [14]:
df=pd.DataFrame(np.arange(1,201).reshape(20,10))
df

0    1    2    3    4    5    6    7    8    9
0     1    2    3    4    5    6    7    8    9   10
1    11   12   13   14   15   16   17   18   19   20
2    21   22   23   24   25   26   27   28   29   30
3    31   32   33   34   35   36   37   38   39   40
4    41   42   43   44   45   46   47   48   49   50
5    51   52   53   54   55   56   57   58   59   60
6    61   62   63   64   65   66   67   68   69   70
7    71   72   73   74   75   76   77   78   79   80
8    81   82   83   84   85   86   87   88   89   90
9    91   92   93   94   95   96   97   98   99  100
10  101  102  103  104  105  106  107  108  109  110
11  111  112  113  114  115  116  117  118  119  120
12  121  122  123  124  125  126  127  128  129  130
13  131  132  133  134  135  136  137  138  139  140
14  141  142  143  144  145  146  147  148  149  150
15  151  152  153  154  155  156  157  158  159  160
16  161  162  163  164  165  166  167  168  169  170
17  171  172  173  174  175  176  177  178  179  180
18  181  182  183  184  185  186  187  188  189  190
19  191  192  193  194  195  196  197  198  199  200

In [15]:
df.head()       #default it shows 5 you can pass the value also

0   1   2   3   4   5   6   7   8   9
0   1   2   3   4   5   6   7   8   9  10
1  11  12  13  14  15  16  17  18  19  20
2  21  22  23  24  25  26  27  28  29  30
3  31  32  33  34  35  36  37  38  39  40
4  41  42  43  44  45  46  47  48  49  50

In [16]:
df.head(10)

0   1   2   3   4   5   6   7   8    9
0   1   2   3   4   5   6   7   8   9   10
1  11  12  13  14  15  16  17  18  19   20
2  21  22  23  24  25  26  27  28  29   30
3  31  32  33  34  35  36  37  38  39   40
4  41  42  43  44  45  46  47  48  49   50
5  51  52  53  54  55  56  57  58  59   60
6  61  62  63  64  65  66  67  68  69   70
7  71  72  73  74  75  76  77  78  79   80
8  81  82  83  84  85  86  87  88  89   90
9  91  92  93  94  95  96  97  98  99  100

In [17]:
df.head(2)

0   1   2   3   4   5   6   7   8   9
0   1   2   3   4   5   6   7   8   9  10
1  11  12  13  14  15  16  17  18  19  20

# tail()

In [20]:
# tail() is used to print the last five elements

In [18]:
df

0    1    2    3    4    5    6    7    8    9
0     1    2    3    4    5    6    7    8    9   10
1    11   12   13   14   15   16   17   18   19   20
2    21   22   23   24   25   26   27   28   29   30
3    31   32   33   34   35   36   37   38   39   40
4    41   42   43   44   45   46   47   48   49   50
5    51   52   53   54   55   56   57   58   59   60
6    61   62   63   64   65   66   67   68   69   70
7    71   72   73   74   75   76   77   78   79   80
8    81   82   83   84   85   86   87   88   89   90
9    91   92   93   94   95   96   97   98   99  100
10  101  102  103  104  105  106  107  108  109  110
11  111  112  113  114  115  116  117  118  119  120
12  121  122  123  124  125  126  127  128  129  130
13  131  132  133  134  135  136  137  138  139  140
14  141  142  143  144  145  146  147  148  149  150
15  151  152  153  154  155  156  157  158  159  160
16  161  162  163  164  165  166  167  168  169  170
17  171  172  173  174  175  176  177  178  179  180
18  181  182  183  184  185  186  187  188  189  190
19  191  192  193  194  195  196  197  198  199  200

In [21]:
df.tail(5)

0    1    2    3    4    5    6    7    8    9
15  151  152  153  154  155  156  157  158  159  160
16  161  162  163  164  165  166  167  168  169  170
17  171  172  173  174  175  176  177  178  179  180
18  181  182  183  184  185  186  187  188  189  190
19  191  192  193  194  195  196  197  198  199  200

In [22]:
df.tail(3)

0    1    2    3    4    5    6    7    8    9
17  171  172  173  174  175  176  177  178  179  180
18  181  182  183  184  185  186  187  188  189  190
19  191  192  193  194  195  196  197  198  199  200

In [23]:
df.describe()

0           1           2           3           4           5  \
count   20.000000   20.000000   20.000000   20.000000   20.000000   20.000000   
mean    96.000000   97.000000   98.000000   99.000000  100.000000  101.000000   
std     59.160798   59.160798   59.160798   59.160798   59.160798   59.160798   
min      1.000000    2.000000    3.000000    4.000000    5.000000    6.000000   
25%     48.500000   49.500000   50.500000   51.500000   52.500000   53.500000   
50%     96.000000   97.000000   98.000000   99.000000  100.000000  101.000000   
75%    143.500000  144.500000  145.500000  146.500000  147.500000  148.500000   
max    191.000000  192.000000  193.000000  194.000000  195.000000  196.000000   

                6           7           8           9  
count   20.000000   20.000000   20.000000   20.000000  
mean   102.000000  103.000000  104.000000  105.000000  
std     59.160798   59.160798   59.160798   59.160798  
min      7.000000    8.000000    9.000000   10.000000  
25%     54.500000   55.500000   56.500000   57.500000  
50%    102.000000  103.000000  104.000000  105.000000  
75%    149.500000  150.500000  151.500000  152.500000  
max    197.000000  198.000000  199.000000  200.000000

In [26]:
df.dtypes   #show the data tyoe

0    int32
1    int32
2    int32
3    int32
4    int32
5    int32
6    int32
7    int32
8    int32
9    int32
dtype: object

In [28]:
df.index         #show all index

RangeIndex(start=0, stop=20, step=1)

In [29]:
df.columns     #show all columns

RangeIndex(start=0, stop=10, step=1)

In [30]:
df.T        #transpose the table

0   1   2   3   4   5   6   7   8    9    10   11   12   13   14   15   16  \
0   1  11  21  31  41  51  61  71  81   91  101  111  121  131  141  151  161   
1   2  12  22  32  42  52  62  72  82   92  102  112  122  132  142  152  162   
2   3  13  23  33  43  53  63  73  83   93  103  113  123  133  143  153  163   
3   4  14  24  34  44  54  64  74  84   94  104  114  124  134  144  154  164   
4   5  15  25  35  45  55  65  75  85   95  105  115  125  135  145  155  165   
5   6  16  26  36  46  56  66  76  86   96  106  116  126  136  146  156  166   
6   7  17  27  37  47  57  67  77  87   97  107  117  127  137  147  157  167   
7   8  18  28  38  48  58  68  78  88   98  108  118  128  138  148  158  168   
8   9  19  29  39  49  59  69  79  89   99  109  119  129  139  149  159  169   
9  10  20  30  40  50  60  70  80  90  100  110  120  130  140  150  160  170   

    17   18   19  
0  171  181  191  
1  172  182  192  
2  173  183  193  
3  174  184  194  
4  175  185  195  
5  176  186  196  
6  177  187  197  
7  178  188  198  
8  179  189  199  
9  180  190  200

In [31]:
#decending order

df.sort_index(axis=0,ascending=False)

0    1    2    3    4    5    6    7    8    9
19  191  192  193  194  195  196  197  198  199  200
18  181  182  183  184  185  186  187  188  189  190
17  171  172  173  174  175  176  177  178  179  180
16  161  162  163  164  165  166  167  168  169  170
15  151  152  153  154  155  156  157  158  159  160
14  141  142  143  144  145  146  147  148  149  150
13  131  132  133  134  135  136  137  138  139  140
12  121  122  123  124  125  126  127  128  129  130
11  111  112  113  114  115  116  117  118  119  120
10  101  102  103  104  105  106  107  108  109  110
9    91   92   93   94   95   96   97   98   99  100
8    81   82   83   84   85   86   87   88   89   90
7    71   72   73   74   75   76   77   78   79   80
6    61   62   63   64   65   66   67   68   69   70
5    51   52   53   54   55   56   57   58   59   60
4    41   42   43   44   45   46   47   48   49   50
3    31   32   33   34   35   36   37   38   39   40
2    21   22   23   24   25   26   27   28   29   30
1    11   12   13   14   15   16   17   18   19   20
0     1    2    3    4    5    6    7    8    9   10

In [32]:
df.sort_index(axis=1,ascending=False)     #column decending order

9    8    7    6    5    4    3    2    1    0
0    10    9    8    7    6    5    4    3    2    1
1    20   19   18   17   16   15   14   13   12   11
2    30   29   28   27   26   25   24   23   22   21
3    40   39   38   37   36   35   34   33   32   31
4    50   49   48   47   46   45   44   43   42   41
5    60   59   58   57   56   55   54   53   52   51
6    70   69   68   67   66   65   64   63   62   61
7    80   79   78   77   76   75   74   73   72   71
8    90   89   88   87   86   85   84   83   82   81
9   100   99   98   97   96   95   94   93   92   91
10  110  109  108  107  106  105  104  103  102  101
11  120  119  118  117  116  115  114  113  112  111
12  130  129  128  127  126  125  124  123  122  121
13  140  139  138  137  136  135  134  133  132  131
14  150  149  148  147  146  145  144  143  142  141
15  160  159  158  157  156  155  154  153  152  151
16  170  169  168  167  166  165  164  163  162  161
17  180  179  178  177  176  175  174  173  172  171
18  190  189  188  187  186  185  184  183  182  181
19  200  199  198  197  196  195  194  193  192  191

In [35]:
dff=pd.read_csv("C:\\Users\\DELL\\Downloads\\tested.csv")  #here we load data set by entering the location

In [36]:
dff

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [37]:
dff.shape

(418, 12)

In [39]:
# head = is used to print first 5 rows from the dataset 
dff.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [40]:
# tail= is used to print last 5 rows from the dataset 
dff.tail()

PassengerId  Survived  Pclass                          Name     Sex  \
413         1305         0       3            Spector, Mr. Woolf    male   
414         1306         1       1  Oliva y Ocana, Dona. Fermina  female   
415         1307         0       3  Saether, Mr. Simon Sivertsen    male   
416         1308         0       3           Ware, Mr. Frederick    male   
417         1309         0       3      Peter, Master. Michael J    male   

      Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
413   NaN      0      0           A.5. 3236    8.0500   NaN        S  
414  39.0      0      0            PC 17758  108.9000  C105        C  
415  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416   NaN      0      0              359309    8.0500   NaN        S  
417   NaN      1      1                2668   22.3583   NaN        C

In [43]:
dff.columns   #show columns name

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [44]:
dff.index   #show index

RangeIndex(start=0, stop=418, step=1)

In [45]:
len(dff)   #show no of rows

418

In [46]:
dff.shape     #showed shape of table

(418, 12)

In [49]:
dff.size      #show the size

5016

In [63]:
418*12


5016

In [71]:
dff1=dff.copy()  #here we create a copy of dff and save it to a variable dff1

In [65]:
dff1

PassengerId  Survived  Pclass  \
0            892         0       3   
1            893         1       3   
2            894         0       2   
3            895         0       3   
4            896         1       3   
..           ...       ...     ...   
413         1305         0       3   
414         1306         1       1   
415         1307         0       3   
416         1308         0       3   
417         1309         0       3   

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0   
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                       Myles, Mr. Thomas Francis    male  62.0      0      0   
3                                Wirz, Mr. Albert    male  27.0      0      0   
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   
..                                            ...     ...   ...    ...    ...   
413                            Spector, Mr. Woolf    male   NaN      0      0   
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0   
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0   
416                           Ware, Mr. Frederick    male   NaN      0      0   
417                      Peter, Master. Michael J    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked  
0                330911    7.8292   NaN        Q  
1                363272    7.0000   NaN        S  
2                240276    9.6875   NaN        Q  
3                315154    8.6625   NaN        S  
4               3101298   12.2875   NaN        S  
..                  ...       ...   ...      ...  
413           A.5. 3236    8.0500   NaN        S  
414            PC 17758  108.9000  C105        C  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  
416              359309    8.0500   NaN        S  
417                2668   22.3583   NaN        C  

[418 rows x 12 columns]

In [66]:
dff1.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [67]:
# drop = used to remove the column 
# axis = 0  -> rows
# axis = 1  -> columns 

In [104]:
dff1=dff1.drop(["Name"],axis=1)

In [107]:
dff1.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch   Ticket  \
0          892         0       3    male  34.5      0      0   330911   
1          893         1       3  female  47.0      1      0   363272   
2          894         0       2    male  62.0      0      0   240276   
3          895         0       3    male  27.0      0      0   315154   
4          896         1       3  female  22.0      1      1  3101298   

      Fare Cabin Embarked  
0   7.8292   NaN        Q  
1   7.0000   NaN        S  
2   9.6875   NaN        Q  
3   8.6625   NaN        S  
4  12.2875   NaN        S

In [108]:
dff1.shape

(418, 11)

In [109]:
# we are having 418 rows so will create 418 values using for loop,and save it in a list , and add it to the dataset 

In [111]:
values=[] #we create a empty list here
for i in range(418):    #i iterate the value one by one 
    values.append(i)      #here we append the value of i in values
    
print(values)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221,

In [112]:
new_values=pd.DataFrame(values)   #creating a dataframe

In [113]:
new_values

0
0      0
1      1
2      2
3      3
4      4
..   ...
413  413
414  414
415  415
416  416
417  417

[418 rows x 1 columns]

In [114]:
#now we want to add new_values in our data

In [116]:
dff1=pd.concat([dff1,new_values],axis=1)   #for adding the columns with values we use concat function

In [117]:
dff1

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            892         0       3    male  34.5      0      0   
1            893         1       3  female  47.0      1      0   
2            894         0       2    male  62.0      0      0   
3            895         0       3    male  27.0      0      0   
4            896         1       3  female  22.0      1      1   
..           ...       ...     ...     ...   ...    ...    ...   
413         1305         0       3    male   NaN      0      0   
414         1306         1       1  female  39.0      0      0   
415         1307         0       3    male  38.5      0      0   
416         1308         0       3    male   NaN      0      0   
417         1309         0       3    male   NaN      1      1   

                 Ticket      Fare Cabin Embarked    0  
0                330911    7.8292   NaN        Q    0  
1                363272    7.0000   NaN        S    1  
2                240276    9.6875   NaN        Q    2  
3                315154    8.6625   NaN        S    3  
4               3101298   12.2875   NaN        S    4  
..                  ...       ...   ...      ...  ...  
413           A.5. 3236    8.0500   NaN        S  413  
414            PC 17758  108.9000  C105        C  414  
415  SOTON/O.Q. 3101262    7.2500   NaN        S  415  
416              359309    8.0500   NaN        S  416  
417                2668   22.3583   NaN        C  417  

[418 rows x 12 columns]

In [118]:
dff1.columns

Index(['PassengerId',    'Survived',      'Pclass',         'Sex',
               'Age',       'SibSp',       'Parch',      'Ticket',
              'Fare',       'Cabin',    'Embarked',             0],
      dtype='object')

In [119]:
#now we want to change the column name (0) to new_values

In [123]:
dff1=dff1.rename(columns={0:"new_values"})     #here we use rename keyword, 0 means column whic we want to rename and new_values means new name

In [122]:
dff1.head(2)

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  Ticket    Fare  \
0          892         0       3    male  34.5      0      0  330911  7.8292   
1          893         1       3  female  47.0      1      0  363272  7.0000   

  Cabin Embarked  new_values  
0   NaN        Q           0  
1   NaN        S           1

In [124]:
dff1["Sex"].unique()    # find the unique 

array(['male', 'female'], dtype=object)

In [126]:
dff1["Pclass"].unique()

array([3, 2, 1], dtype=int64)

### Note---- 
unique keyword is used to find the unique values

In [127]:
# how many time male and female are there 

dff1["Sex"].value_counts()

male      266
female    152
Name: Sex, dtype: int64

In [128]:
dff1["Pclass"].value_counts()

3    218
1    107
2     93
Name: Pclass, dtype: int64

### Note---

Value_counts() keyword is used to find how many times unique elements are there

In [129]:
# find the null values : 
# null values means no data in the particular location 


In [130]:
dff1.isnull()

PassengerId  Survived  Pclass    Sex    Age  SibSp  Parch  Ticket   Fare  \
0          False     False   False  False  False  False  False   False  False   
1          False     False   False  False  False  False  False   False  False   
2          False     False   False  False  False  False  False   False  False   
3          False     False   False  False  False  False  False   False  False   
4          False     False   False  False  False  False  False   False  False   
..           ...       ...     ...    ...    ...    ...    ...     ...    ...   
413        False     False   False  False   True  False  False   False  False   
414        False     False   False  False  False  False  False   False  False   
415        False     False   False  False  False  False  False   False  False   
416        False     False   False  False   True  False  False   False  False   
417        False     False   False  False   True  False  False   False  False   

     Cabin  Embarked  new_values  
0     True     False       False  
1     True     False       False  
2     True     False       False  
3     True     False       False  
4     True     False       False  
..     ...       ...         ...  
413   True     False       False  
414  False     False       False  
415   True     False       False  
416   True     False       False  
417   True     False       False  

[418 rows x 12 columns]

### Isnull() is used to find the null values

In [131]:
# u can find the count also 

dff1.isnull().sum()   # it is used to give complete null values information 

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
new_values       0
dtype: int64

In [132]:
dff1.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch   Ticket  \
0          892         0       3    male  34.5      0      0   330911   
1          893         1       3  female  47.0      1      0   363272   
2          894         0       2    male  62.0      0      0   240276   
3          895         0       3    male  27.0      0      0   315154   
4          896         1       3  female  22.0      1      1  3101298   

      Fare Cabin Embarked  new_values  
0   7.8292   NaN        Q           0  
1   7.0000   NaN        S           1  
2   9.6875   NaN        Q           2  
3   8.6625   NaN        S           3  
4  12.2875   NaN        S           4

In [136]:
dff1.head()["Age"]

0    34.5
1    47.0
2    62.0
3    27.0
4    22.0
Name: Age, dtype: float64

In [137]:
dff1["Age"]=dff1["Age"].fillna(10.0)  #fillna is used to fill null values

In [138]:
dff1.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch   Ticket  \
0          892         0       3    male  34.5      0      0   330911   
1          893         1       3  female  47.0      1      0   363272   
2          894         0       2    male  62.0      0      0   240276   
3          895         0       3    male  27.0      0      0   315154   
4          896         1       3  female  22.0      1      1  3101298   

      Fare Cabin Embarked  new_values  
0   7.8292   NaN        Q           0  
1   7.0000   NaN        S           1  
2   9.6875   NaN        Q           2  
3   8.6625   NaN        S           3  
4  12.2875   NaN        S           4

In [139]:
dff1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
new_values       0
dtype: int64

# select_dtype we can select numerical and categorical columns

In [140]:
dff1.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch   Ticket  \
0          892         0       3    male  34.5      0      0   330911   
1          893         1       3  female  47.0      1      0   363272   
2          894         0       2    male  62.0      0      0   240276   
3          895         0       3    male  27.0      0      0   315154   
4          896         1       3  female  22.0      1      1  3101298   

      Fare Cabin Embarked  new_values  
0   7.8292   NaN        Q           0  
1   7.0000   NaN        S           1  
2   9.6875   NaN        Q           2  
3   8.6625   NaN        S           3  
4  12.2875   NaN        S           4

In [141]:
numerical_data = dff1.select_dtypes(exclude='object')   #seperate numerical data
numerical_data

PassengerId  Survived  Pclass   Age  SibSp  Parch      Fare  new_values
0            892         0       3  34.5      0      0    7.8292           0
1            893         1       3  47.0      1      0    7.0000           1
2            894         0       2  62.0      0      0    9.6875           2
3            895         0       3  27.0      0      0    8.6625           3
4            896         1       3  22.0      1      1   12.2875           4
..           ...       ...     ...   ...    ...    ...       ...         ...
413         1305         0       3  10.0      0      0    8.0500         413
414         1306         1       1  39.0      0      0  108.9000         414
415         1307         0       3  38.5      0      0    7.2500         415
416         1308         0       3  10.0      0      0    8.0500         416
417         1309         0       3  10.0      1      1   22.3583         417

[418 rows x 8 columns]

In [142]:
cate = dff1.select_dtypes(include ='object')            # selecting cateogorical data
cate

Sex              Ticket Cabin Embarked
0      male              330911   NaN        Q
1    female              363272   NaN        S
2      male              240276   NaN        Q
3      male              315154   NaN        S
4    female             3101298   NaN        S
..      ...                 ...   ...      ...
413    male           A.5. 3236   NaN        S
414  female            PC 17758  C105        C
415    male  SOTON/O.Q. 3101262   NaN        S
416    male              359309   NaN        S
417    male                2668   NaN        C

[418 rows x 4 columns]

In [145]:
dff1[["Sex","Cabin","Parch"]]

Sex Cabin  Parch
0      male   NaN      0
1    female   NaN      0
2      male   NaN      0
3      male   NaN      0
4    female   NaN      1
..      ...   ...    ...
413    male   NaN      0
414  female  C105      0
415    male   NaN      0
416    male   NaN      0
417    male   NaN      1

[418 rows x 3 columns]

In [146]:
dff1['Sex'] = dff1['Sex'].map({'male': 10 , 'female': 11})

In [147]:
dff1

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch  \
0            892         0       3   10  34.5      0      0   
1            893         1       3   11  47.0      1      0   
2            894         0       2   10  62.0      0      0   
3            895         0       3   10  27.0      0      0   
4            896         1       3   11  22.0      1      1   
..           ...       ...     ...  ...   ...    ...    ...   
413         1305         0       3   10  10.0      0      0   
414         1306         1       1   11  39.0      0      0   
415         1307         0       3   10  38.5      0      0   
416         1308         0       3   10  10.0      0      0   
417         1309         0       3   10  10.0      1      1   

                 Ticket      Fare Cabin Embarked  new_values  
0                330911    7.8292   NaN        Q           0  
1                363272    7.0000   NaN        S           1  
2                240276    9.6875   NaN        Q           2  
3                315154    8.6625   NaN        S           3  
4               3101298   12.2875   NaN        S           4  
..                  ...       ...   ...      ...         ...  
413           A.5. 3236    8.0500   NaN        S         413  
414            PC 17758  108.9000  C105        C         414  
415  SOTON/O.Q. 3101262    7.2500   NaN        S         415  
416              359309    8.0500   NaN        S         416  
417                2668   22.3583   NaN        C         417  

[418 rows x 12 columns]

In [153]:
# describe = is used to check the statistical information of the data 

dff1.describe()

PassengerId    Survived      Pclass         Sex         Age  \
count   418.000000  418.000000  418.000000  418.000000  418.000000   
mean   1100.500000    0.363636    2.265550   10.363636   26.101675   
std     120.810458    0.481622    0.841838    0.481622   15.064901   
min     892.000000    0.000000    1.000000   10.000000    0.170000   
25%     996.250000    0.000000    1.000000   10.000000   10.000000   
50%    1100.500000    0.000000    3.000000   10.000000   24.000000   
75%    1204.750000    1.000000    3.000000   11.000000   35.750000   
max    1309.000000    1.000000    3.000000   11.000000   76.000000   

            SibSp       Parch        Fare  new_values  
count  418.000000  418.000000  417.000000  418.000000  
mean     0.447368    0.392344   35.627188  208.500000  
std      0.896760    0.981429   55.907576  120.810458  
min      0.000000    0.000000    0.000000    0.000000  
25%      0.000000    0.000000    7.895800  104.250000  
50%      0.000000    0.000000   14.454200  208.500000  
75%      1.000000    0.000000   31.500000  312.750000  
max      8.000000    9.000000  512.329200  417.000000

In [154]:
# info = is used to check the complete information about the dataset 
dff1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  418 non-null    int64  
 1   Survived     418 non-null    int64  
 2   Pclass       418 non-null    int64  
 3   Sex          418 non-null    int64  
 4   Age          418 non-null    float64
 5   SibSp        418 non-null    int64  
 6   Parch        418 non-null    int64  
 7   Ticket       418 non-null    object 
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object 
 10  Embarked     418 non-null    object 
 11  new_values   418 non-null    int64  
dtypes: float64(2), int64(7), object(3)
memory usage: 39.3+ KB


In [156]:
#we want to sort the value 
dff1.sort_values(by="Fare",ascending=True)

PassengerId  Survived  Pclass  Sex   Age  SibSp  Parch    Ticket  \
266         1158         0       1   10  10.0      0      0    112051   
372         1264         0       1   10  49.0      0      0    112058   
21           913         0       3   10   9.0      0      1   C 17368   
133         1025         0       3   10  10.0      1      0      2621   
116         1008         0       3   10  10.0      0      0      2681   
..           ...       ...     ...  ...   ...    ...    ...       ...   
59           951         1       1   11  36.0      0      0  PC 17608   
53           945         1       1   11  28.0      3      2     19950   
69           961         1       1   11  60.0      1      4     19950   
343         1235         1       1   11  58.0      0      1  PC 17755   
152         1044         0       3   10  60.5      0      0      3701   

         Fare        Cabin Embarked  new_values  
266    0.0000          NaN        S         266  
372    0.0000  B52 B54 B56        S         372  
21     3.1708          NaN        S          21  
133    6.4375          NaN        C         133  
116    6.4375          NaN        C         116  
..        ...          ...      ...         ...  
59   262.3750          B61        C          59  
53   263.0000  C23 C25 C27        S          53  
69   263.0000  C23 C25 C27        S          69  
343  512.3292  B51 B53 B55        C         343  
152       NaN          NaN        S         152  

[418 rows x 12 columns]

# groupby function

In [148]:
a = pd.DataFrame(
    {'Animal': ['Falcon', 'Falcon','Parrot', 'Parrot'],
     'Max Speed': [380., 370., 24., 26.]}
                )

a

Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [149]:
a.groupby(['Animal']).mean()

Max Speed
Animal           
Falcon      375.0
Parrot       25.0

In [151]:
(380+370)/2


375.0

# Pandas duplicate concept

In [152]:
a = pd.DataFrame({'col 1' : [1,2,2,3,3,3,4,4],
                   'col 2' : ['a','b','b','c','c','c','d','c'],
                    'col 2' : ['A','B','B','C','C','C','D','D']})
a  # 3rd one will overwrite the 2nd one 


col 1 col 2
0      1     A
1      2     B
2      2     B
3      3     C
4      3     C
5      3     C
6      4     D
7      4     D